### ISSUE TITLE
unknown config attribute params.projectDir

### ISSUE THREAD

**Issue by babramso** [epi2me-labs/wf-clone-validation#2]
I'm not really familiar with nextflow and unsure how to handle this.

root@MSI:/mnt/c/Users/theab/Documents# nextflow run epi2me-labs/wf-clone-validation --help
N E X T F L O W  ~  version 19.01.0
Launching `epi2me-labs/wf-clone-validation` [sharp_swartz] - revision: 4048ddebdc [master]
ERROR ~ Unknown config attribute `params.projectDir` -- check config file: /root/.nextflow/assets/epi2me-labs/wf-clone-validation/nextflow.config

 -- Check '.nextflow.log' file for details

###Contents of the  '.nextflow.log'
root@MSI:/mnt/c/Users/theab/Documents# cat .nextflow.log
Nov-02 17:06:46.163 [main] DEBUG nextflow.cli.Launcher - $> nextflow run epi2me-labs/wf-clone-validation --help
Nov-02 17:06:46.270 [main] INFO  nextflow.cli.CmdRun - N E X T F L O W  ~  version 19.01.0
Nov-02 17:06:46.693 [main] DEBUG nextflow.scm.AssetManager - Git config: /root/.nextflow/assets/epi2me-labs/wf-clone-validation/.git/config; branch: master; remote: origin; url: https://github.com/epi2me-labs/wf-clone-validation.git
Nov-02 17:06:46.701 [main] DEBUG nextflow.scm.AssetManager - Git config: /root/.nextflow/assets/epi2me-labs/wf-clone-validation/.git/config; branch: master; remote: origin; url: https://github.com/epi2me-labs/wf-clone-validation.git
Nov-02 17:06:46.784 [main] DEBUG nextflow.scm.AssetManager - Git config: /root/.nextflow/assets/epi2me-labs/wf-clone-validation/.git/config; branch: master; remote: origin; url: https://github.com/epi2me-labs/wf-clone-validation.git
Nov-02 17:06:46.784 [main] INFO  nextflow.cli.CmdRun - Launching `epi2me-labs/wf-clone-validation` [sharp_swartz] - revision: 4048ddebdc [master]
Nov-02 17:06:47.268 [main] DEBUG nextflow.config.ConfigBuilder - Found config base: /root/.nextflow/assets/epi2me-labs/wf-clone-validation/nextflow.config    
Nov-02 17:06:47.270 [main] DEBUG nextflow.config.ConfigBuilder - Parsing config file: /root/.nextflow/assets/epi2me-labs/wf-clone-validation/nextflow.config  
Nov-02 17:06:47.276 [main] DEBUG nextflow.config.ConfigBuilder - Applying config profile: `standard`
Nov-02 17:06:47.360 [main] DEBUG nextflow.config.ConfigBuilder - In the following config object the attribute `params.projectDir` is empty:
  help=true
  out_dir='output'
  wfversion='v0.1.4'
  fastq=null
  db_directory=null
  sanitize_fastq=false
  samples=null
  threads=4
  host_reference='NO_HOST_REF'
  regions_bedfile='NO_REG_BED'
  approx_size=7000
  assm_coverage=60
  trim_length=150
  canu_useGrid=false
  prefix=null
  min_barcode=null
  max_barcode=null
  primers=[:]/data/primers.tsv
  reference=null
  report_name='report'
  monochrome_logs=false
  validate_params=true
  show_hidden_params=false
  schema_ignore_params='show_hidden_params,validate_params,monochrome_logs,aws_queue,aws_image_prefix,wfversion'

Nov-02 17:06:47.365 [main] ERROR nextflow.cli.Launcher - Unknown config attribute `params.projectDir` -- check config file: /root/.nextflow/assets/epi2me-labs/wf-clone-validation/nextflow.config
nextflow.exception.ConfigParseException: Unknown config attribute `params.projectDir` -- check config file: /root/.nextflow/assets/epi2me-labs/wf-clone-validation/nextflow.config
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
        at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:83)
        at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:77)
        at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:84)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:59)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:237)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:249)
        at nextflow.config.ConfigBuilder.validate(ConfigBuilder.groovy:400)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:190)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:58)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:156)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:184)
        at nextflow.config.ConfigBuilder.validate(ConfigBuilder.groovy:402)
        at nextflow.config.ConfigBuilder.validate(ConfigBuilder.groovy)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:190)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:58)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:156)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:176)
        at nextflow.config.ConfigBuilder.merge0(ConfigBuilder.groovy:367)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:190)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:58)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:156)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:184)
        at nextflow.config.ConfigBuilder.buildConfig0(ConfigBuilder.groovy:316)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:190)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:58)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:156)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:176)
        at nextflow.config.ConfigBuilder.buildGivenFiles(ConfigBuilder.groovy:282)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:190)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:58)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:156)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:168)
        at nextflow.config.ConfigBuilder.buildConfigObject(ConfigBuilder.groovy:633)
        at nextflow.config.ConfigBuilder.build(ConfigBuilder.groovy:646)
        at nextflow.script.ScriptRunner.<init>(ScriptRunner.groovy:121)
        at nextflow.cli.CmdRun.run(CmdRun.groovy:223)
        at nextflow.cli.Launcher.run(Launcher.groovy:445)
        at nextflow.cli.Launcher.main(Launcher.groovy:622)

**Comment by sarahjeeeze** [comment]
Hi, I think its because the version of Nextflow needs to be 20+. You can update using the cmd `nextflow self-update`. Also see here - https://www.nextflow.io/docs/latest/getstarted.html
