### ISSUE TITLE
[Bug]: basecaller_cfg error

### ISSUE THREAD

**Issue by CESTechSupport** [epi2me-labs/wf-clone-validation#25]
### What happened?

When we run the workflow (wf-clone-validation) from EPI2ME, we get this error. 
We selected 'dna_r10.4.1_e8.2_400bps_sup@v3.5.2' as baescaller_cfg. 

RuntimeError: Error validating model from '--model' argument: Model r1041_e82_400bps_sup_g632 is not a known model or existant file..

Replacing the Medaka model name would not work as well. 

### Operating System

Windows 11

### Workflow Execution

EPI2ME Labs desktop application

### Workflow Execution - EPI2ME Labs Versions

wf-clone-validation

### Workflow Execution - CLI Execution Profile

None

### Workflow Version

v0.3.1

### Relevant log output

```shell
This is epi2me-labs/wf-clone-validation v0.3.1.
--------------------------------------------------------------------------------
Checking fastq input.
[57/91b7b4] Submitted process > fastcat (2)
[c8/c8e944] Submitted process > fastcat (1)
[a3/3adc34] Submitted process > pipeline:medakaVersion
[46/be0d67] Submitted process > pipeline:getParams
[fa/8dc719] Submitted process > pipeline:lookup_medaka_model (1)
[25/de4543] Submitted process > pipeline:getVersions
[f9/32eebf] Submitted process > pipeline:checkIfEnoughReads (1)
[d8/3f8fd5] Submitted process > pipeline:checkIfEnoughReads (2)
[a6/c38bc2] Submitted process > pipeline:assembleCore (1)
[99/1c84f8] Submitted process > pipeline:assembleCore (2)
[3c/8781d1] Submitted process > pipeline:downsampledStats (1)
[96/83b629] Submitted process > pipeline:downsampledStats (2)
[a6/953b11] Submitted process > pipeline:medakaPolishAssembly (2)
[61/98f9b6] Submitted process > pipeline:medakaPolishAssembly (1)
ERROR ~ Error executing process > 'pipeline:medakaPolishAssembly (2)'
Caused by:
  Process `pipeline:medakaPolishAssembly (2)` terminated with an error exit status (1)
Command executed:
  STATUS="Failed to polish assembly with Medaka"
      medaka_consensus -i "barcode23.downsampled.fastq" -d "barcode23.reconciled.fasta" -m "r1041_e82_400bps_sup_g632
  " -o . -t 4 -f
      echo ">barcode23" >> "barcode23.final.fasta"
      sed "2q;d" consensus.fasta >> "barcode23.final.fasta"
      STATUS="Completed successfully"
Command exit status:
  1
Command output:
  (empty)
Command error:
  Traceback (most recent call last):
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/medaka/medaka.py", line 35, in __call__
      model_fp = medaka.models.resolve_model(val)
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/medaka/models.py", line 31, in resolve_model
      raise ValueError(
  ValueError: Model r1041_e82_400bps_sup_g632 is not a known model or existant file.
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/home/epi2melabs/conda/bin/medaka", line 11, in <module>
      sys.exit(main())
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/medaka/medaka.py", line 703, in main
      args = parser.parse_args()
    File "/home/epi2melabs/conda/lib/python3.8/argparse.py", line 1768, in parse_args
      args, argv = self.parse_known_args(args, namespace)
    File "/home/epi2melabs/conda/lib/python3.8/argparse.py", line 1800, in parse_known_args
      namespace, args = self._parse_known_args(args, namespace)
    File "/home/epi2melabs/conda/lib/python3.8/argparse.py", line 1988, in _parse_known_args
      positionals_end_index = consume_positionals(start_index)
    File "/home/epi2melabs/conda/lib/python3.8/argparse.py", line 1965, in consume_positionals
      take_action(action, args)
    File "/home/epi2melabs/conda/lib/python3.8/argparse.py", line 1874, in take_action
      action(self, namespace, argument_values, option_string)
    File "/home/epi2melabs/conda/lib/python3.8/argparse.py", line 1159, in __call__
      subnamespace, arg_strings = parser.parse_known_args(arg_strings, None)
    File "/home/epi2melabs/conda/lib/python3.8/argparse.py", line 1800, in parse_known_args
      namespace, args = self._parse_known_args(args, namespace)
    File "/home/epi2melabs/conda/lib/python3.8/argparse.py", line 1988, in _parse_known_args
      positionals_end_index = consume_positionals(start_index)
    File "/home/epi2melabs/conda/lib/python3.8/argparse.py", line 1965, in consume_positionals
      take_action(action, args)
    File "/home/epi2melabs/conda/lib/python3.8/argparse.py", line 1874, in take_action
      action(self, namespace, argument_values, option_string)
    File "/home/epi2melabs/conda/lib/python3.8/argparse.py", line 1159, in __call__
      subnamespace, arg_strings = parser.parse_known_args(arg_strings, None)
    File "/home/epi2melabs/conda/lib/python3.8/argparse.py", line 1800, in parse_known_args
      namespace, args = self._parse_known_args(args, namespace)
    File "/home/epi2melabs/conda/lib/python3.8/argparse.py", line 2006, in _parse_known_args
      start_index = consume_optional(start_index)
    File "/home/epi2melabs/conda/lib/python3.8/argparse.py", line 1946, in consume_optional
      take_action(action, args, option_string)
    File "/home/epi2melabs/conda/lib/python3.8/argparse.py", line 1874, in take_action
      action(self, namespace, argument_values, option_string)
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/medaka/medaka.py", line 38, in __call__
      raise RuntimeError(msg.format(self.dest, str(e)))
  RuntimeError: Error validating model from '--model' argument: Model r1041_e82_400bps_sup_g632 is not a known model or existant file..
Work dir:
  /mnt/wsl/docker-desktop-bind-mounts/Ubuntu/9a345af3fbb9581a8ed854397ac2a87fe36fccbb2066b164f23fa14d09831a3d/instances/wf-clone-validation_69996ae7-0ff7-43ec-82ab-d0c3eae5c3be/work/a6/953b11a9b71195177e3c244557832c
Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`
 -- Check '/mnt/wsl/docker-desktop-bind-mounts/Ubuntu/9a345af3fbb9581a8ed854397ac2a87fe36fccbb2066b164f23fa14d09831a3d/instances/wf-clone-validation_69996ae7-0ff7-43ec-82ab-d0c3eae5c3be/nextflow.log' file for details
WARN: Killing running tasks (1)
```

**Comment by sarahjeeeze** [comment]
Hi, thanks for the feedback. We will look in to this and add a fix shortly.

**Comment by ChristopherRichie** [comment]
I encountered the same issue with wf-clone-validation v0.3.1-g97e1eab, when trying to use r1041_e82_400bps_sup_g632  today.

#FAILED
#for wf-basecalling... basecaller_config="dna_r10.4.1_e8.2_400bps_sup@v3.5.2"  
#for wf-clone-validation... medaka_model="r1041_e82_400bps_sup_g632"

#WORKED switching to "hac" config was successful.
basecaller_config="dna_r10.4.1_e8.2_400bps_hac@v3.5.2"
medaka_model="r1041_e82_400bps_hac_g632"

**Comment by sarahjeeeze** [comment]
Hi, we updated the basecaller models available in v0.5.0 to the latest available in Medaka.

**Comment by sarahjeeeze** [comment]
Closing through lack to response, and this should now be fixed.

**Comment by ChristopherRichie** [comment]
as of 0.5.1 appears to be working
thanks!
