### ISSUE TITLE
Error executing Plannotate

### ISSUE THREAD

**Issue by gabyrech** [epi2me-labs/wf-clone-validation#31]
### Operating System

Ubuntu 22.04

### Workflow Version

v0.5.0

### Workflow Execution

EPI2ME Desktop application

### Workflow Execution - CLI Execution Profile

standard (default)

### What happened?

Error during execution of **Plannotate**

### Relevant log output

```shell
Sep-19 23:10:45.576 [Task monitor] DEBUG n.processor.TaskPollingMonitor - !! executor local > tasks to be completed: 1 -- submitted tasks are shown below
~> TaskHandler[id: 86; name: pipeline:runPlannotate (1); status: RUNNING; exit: -; error: -; workDir: /home/grid/epi2melabs/instances/wf-clone-validation_01HAQJFP21Y7P0PTSBW024VTW0/work/2f/90d63b13529ecb3fec068f563d70dd]
Sep-19 23:15:45.637 [Task monitor] DEBUG n.processor.TaskPollingMonitor - !! executor local > tasks to be completed: 1 -- submitted tasks are shown below
~> TaskHandler[id: 86; name: pipeline:runPlannotate (1); status: RUNNING; exit: -; error: -; workDir: /home/grid/epi2melabs/instances/wf-clone-validation_01HAQJFP21Y7P0PTSBW024VTW0/work/2f/90d63b13529ecb3fec068f563d70dd]
Sep-19 23:20:31.573 [Task monitor] DEBUG n.processor.TaskPollingMonitor - Task completed > TaskHandler[id: 86; name: pipeline:runPlannotate (1); status: COMPLETED; exit: 1; error: -; workDir: /home/grid/epi2melabs/instances/wf-clone-validation_01HAQJFP21Y7P0PTSBW024VTW0/work/2f/90d63b13529ecb3fec068f563d70dd]
Sep-19 23:20:31.575 [Task monitor] DEBUG nextflow.processor.TaskProcessor - Handling unexpected condition for
  task: name=pipeline:runPlannotate (1); work-dir=/home/grid/epi2melabs/instances/wf-clone-validation_01HAQJFP21Y7P0PTSBW024VTW0/work/2f/90d63b13529ecb3fec068f563d70dd
  error [nextflow.exception.ProcessFailedException]: Process `pipeline:runPlannotate (1)` terminated with an error exit status (1)
Sep-19 23:20:31.580 [Task monitor] ERROR nextflow.processor.TaskProcessor - Error executing process > 'pipeline:runPlannotate (1)'

Caused by:
  Process `pipeline:runPlannotate (1)` terminated with an error exit status (1)

Command executed:

  if [ -e "assemblies/OPTIONAL_FILE" ]; then
      assemblies=""
  else
      assemblies="--sequences assemblies/"
  fi
  workflow-glue run_plannotate $assemblies --database Default

Command exit status:
  1

Command output:
  (empty)

Command error:
  More information [in our docs](https://docs.streamlit.io/library/advanced-features/caching).
  2023-09-19 23:12:30.376 `st.cache` is deprecated. Please use one of Streamlit's new caching commands,
  `st.cache_data` or `st.cache_resource`.
  
  More information [in our docs](https://docs.streamlit.io/library/advanced-features/caching).
  Traceback (most recent call last):
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/streamlit/runtime/legacy_caching/caching.py", line 678, in get_or_create_cached_value
      return_value = _read_from_cache(
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/streamlit/runtime/legacy_caching/caching.py", line 435, in _read_from_cache
      raise e
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/streamlit/runtime/legacy_caching/caching.py", line 420, in _read_from_cache
      return _read_from_mem_cache(
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/streamlit/runtime/legacy_caching/caching.py", line 337, in _read_from_mem_cache
      raise CacheKeyNotFoundError("Key not found in mem cache")
  streamlit.runtime.legacy_caching.caching.CacheKeyNotFoundError: Key not found in mem cache
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/home/grid/epi2melabs/workflows/epi2me-labs/wf-clone-validation/bin/workflow-glue", line 7, in <module>
      cli()
    File "/home/grid/epi2melabs/workflows/epi2me-labs/wf-clone-validation/bin/workflow_glue/__init__.py", line 72, in cli
      args.func(args)
    File "/home/grid/epi2melabs/workflows/epi2me-labs/wf-clone-validation/bin/workflow_glue/run_plannotate.py", line 213, in main
      tup_dic, report, plannotate_dic = attempt_annotation(
    File "/home/grid/epi2melabs/workflows/epi2me-labs/wf-clone-validation/bin/workflow_glue/run_plannotate.py", line 183, in attempt_annotation
      tup_dic, clean_df = per_assembly(sample_file, name)
    File "/home/grid/epi2melabs/workflows/epi2me-labs/wf-clone-validation/bin/workflow_glue/run_plannotate.py", line 83, in per_assembly
      plot, annotations, clean_df = run_plannotate(sample_file)
    File "/home/grid/epi2melabs/workflows/epi2me-labs/wf-clone-validation/bin/workflow_glue/run_plannotate.py", line 21, in run_plannotate
      df = annotate(
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/plannotate/annotate.py", line 344, in annotate
      blastDf = get_raw_hits(query, linear, yaml_file)
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/streamlit/runtime/legacy_caching/caching.py", line 717, in wrapped_func
      return get_or_create_cached_value()
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/streamlit/runtime/legacy_caching/caching.py", line 694, in get_or_create_cached_value
      return_value = non_optional_func(*args, **kwargs)
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/plannotate/annotate.py", line 290, in get_raw_hits
      feat_descriptions = get_details(hits, yaml_file_loc)
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/plannotate/annotate.py", line 236, in get_details
      feat_desc = parse_gz(sseqids, details_file_loc) 
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/plannotate/annotate.py", line 198, in parse_gz
      subprocess.call(f'rg -z "{hits}" {gz_loc} > {output.name}',shell = True)
    File "/home/epi2melabs/conda/lib/python3.8/subprocess.py", line 340, in call
      with Popen(*popenargs, **kwargs) as p:
    File "/home/epi2melabs/conda/lib/python3.8/subprocess.py", line 858, in __init__
      self._execute_child(args, executable, preexec_fn, close_fds,
    File "/home/epi2melabs/conda/lib/python3.8/subprocess.py", line 1720, in _execute_child
      raise child_exception_type(errno_num, err_msg, err_filename)
  OSError: [Errno 7] Argument list too long: '/bin/sh'

Work dir:
  /home/grid/epi2melabs/instances/wf-clone-validation_01HAQJFP21Y7P0PTSBW024VTW0/work/2f/90d63b13529ecb3fec068f563d70dd
```

**Comment by sarahjeeeze** [comment]
Hi, thanks for reporting this, we will try to recreate your error and get back to you.

**Comment by sarahjeeeze** [comment]
Hi, I've not been able to recreate the error. Would you be able to update to v0.5.1 also are you on  v5.1.2 of the desktop application? Does the workflow run successfully if you run the demo dataset?

**Comment by gabyrech** [comment]
Thanks @sarahjeeeze ! Updating the workflow to v0.5.1 fixed the issue with Plannotate!
