### ISSUE TITLE
[Bug]: Failed to polish assembly with Medaka

### ISSUE THREAD

**Issue by ONT-Tseng** [epi2me-labs/wf-clone-validation#9]
### What happened?

I used sample data and ran nextflow run locally on my terminal "epi2me-labs/wf-clone-validation --fastq test_reads --db_directory wf-clone-validation-db --threads 4" as instructed in the Github page. It generated errors due to Medaka polish pipeline. I have seen this in the issues page on Gitbhu. Just wondering if this will be fixed in the next version? I also tried other workflows, such as wf-alignment and wf-human-snp and both of them are fine.

### Operating System

Windows 10

### Workflow Execution

Command line

### Workflow Version

Nextflow 22.04.0

### Relevant log output

```shell
Error executing process > 'pipeline:medakaPolishAssembly (1)'

Caused by:
  Process `pipeline:medakaPolishAssembly (1)` terminated with an error exit status (1)

Command executed:

  STATUS="Failed to polish assembly with Medaka"
  medaka_consensus -i Barcode1.downsampled.fastq -d Barcode1.reconciled.fasta -m r941_min_high_g360 -o . -t 4 -f
  echo ">Barcode1" >> Barcode1.final.fasta
  sed "2q;d" consensus.fasta >> Barcode1.final.fasta
  STATUS="Completed successfully"

Command exit status:
  1

Command output:
  (empty)

Command error:
  Traceback (most recent call last):
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/medaka/medaka.py", line 35, in __call__
      model_fp = medaka.models.resolve_model(val)
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/medaka/models.py", line 66, in resolve_model
      raise DownloadError(
  medaka.models.DownloadError: The model file for r941_min_high_g360 is not already installed and could not be downloaded. Check you are connected to the internet and try again.

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "/home/epi2melabs/conda/bin/medaka", line 11, in <module>
      sys.exit(main())
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/medaka/medaka.py", line 699, in main
      args = parser.parse_args()
    File "/home/epi2melabs/conda/lib/python3.8/argparse.py", line 1768, in parse_args
      args, argv = self.parse_known_args(args, namespace)
    File "/home/epi2melabs/conda/lib/python3.8/argparse.py", line 1800, in parse_known_args
      namespace, args = self._parse_known_args(args, namespace)
    File "/home/epi2melabs/conda/lib/python3.8/argparse.py", line 1988, in _parse_known_args
      positionals_end_index = consume_positionals(start_index)
    File "/home/epi2melabs/conda/lib/python3.8/argparse.py", line 1965, in consume_positionals
      take_action(action, args)
    File "/home/epi2melabs/conda/lib/python3.8/argparse.py", line 1874, in take_action
      action(self, namespace, argument_values, option_string)
    File "/home/epi2melabs/conda/lib/python3.8/argparse.py", line 1159, in __call__
      subnamespace, arg_strings = parser.parse_known_args(arg_strings, None)
    File "/home/epi2melabs/conda/lib/python3.8/argparse.py", line 1800, in parse_known_args
      namespace, args = self._parse_known_args(args, namespace)
    File "/home/epi2melabs/conda/lib/python3.8/argparse.py", line 1988, in _parse_known_args
      positionals_end_index = consume_positionals(start_index)
    File "/home/epi2melabs/conda/lib/python3.8/argparse.py", line 1965, in consume_positionals
      take_action(action, args)
    File "/home/epi2melabs/conda/lib/python3.8/argparse.py", line 1874, in take_action
      action(self, namespace, argument_values, option_string)
    File "/home/epi2melabs/conda/lib/python3.8/argparse.py", line 1159, in __call__
      subnamespace, arg_strings = parser.parse_known_args(arg_strings, None)
    File "/home/epi2melabs/conda/lib/python3.8/argparse.py", line 1800, in parse_known_args
      namespace, args = self._parse_known_args(args, namespace)
    File "/home/epi2melabs/conda/lib/python3.8/argparse.py", line 2006, in _parse_known_args
      start_index = consume_optional(start_index)
    File "/home/epi2melabs/conda/lib/python3.8/argparse.py", line 1946, in consume_optional
      take_action(action, args, option_string)
    File "/home/epi2melabs/conda/lib/python3.8/argparse.py", line 1874, in take_action
      action(self, namespace, argument_values, option_string)
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/medaka/medaka.py", line 38, in __call__
      raise RuntimeError(msg.format(self.dest, str(e)))
  RuntimeError: Error validating model from '--model' argument: The model file for r941_min_high_g360 is not already installed and could not be downloaded. Check you are connected to the internet and try again..

Work dir:
  /home/rtseng/test_data/wf-clone-validation/work/ac/cb6b807b71677f32ad55debed86676

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`
```

**Comment by sarahjeeeze** [comment]
Hi, I have been unable to recreate your error on windows. Are you using wsl on windows and are you running it whilst on a vpn/can you connect to the internet from wsl?

**Comment by ONT-Tseng** [comment]
I used ubuntu terminal but not WSL or bash terminal.
Using different terminals can avoid error that I generated?
It seems to be related to polish workflow because steps before it can be run successfully based what have been shown on the terminal.

I have internet as I can ping website (e.g google.com).

**Comment by sarahjeeeze** [comment]
Ubuntu for windows uses WSL so should be fine running from Ubuntu. Are you using docker? It might be that it cant reach the internet from within docker. Maybe try eg. ``` docker run busybox nslookup google.com``` and see if it can reach the internet.

**Comment by twierik** [comment]
I am experiencing the same issue while running in a Singularity container. Can't get downloading this model to work. I tried to manually run medaka in the container using the r941_min_hac_g507 model and this does work because it's pre-installed with Medaka. Is there a way to configure the workflow to use another model?

**Comment by sarahjeeeze** [comment]
Closing through lack of response from original poster.
